"""Константы проекта quiz."""

CATEGORY_TITLE_MAX_LENGTH = 100
QUIZ_TITLE_MAX_LENGTH = 200
QUIZ_DESCRIPTION_MAX_LENGTH = 500

QUESTION_TEXT_MAX_LENGTH = 500
QUESTION_DESCRIPTION_MAX_LENGTH = 500
QUESTION_CORRECT_ANSWER_MAX_LENGTH = 500
QUESTION_EXPLANATION_MAX_LENGTH = 250

DIFFICULTY_EASY = 'easy'
DIFFICULTY_MEDIUM = 'medium'
DIFFICULTY_HARD = 'hard'

DIFFICULTY_CHOICES = [
    (DIFFICULTY_EASY, 'Лёгкий'),
    (DIFFICULTY_MEDIUM, 'Средний'),
    (DIFFICULTY_HARD, 'Сложный'),
]


DIFFICULTY_MAX_LENGTH = max(len(choice) for choice, _ in DIFFICULTY_CHOICES)
